### ISSUE TITLE
How to remove vector from the index?

### ISSUE THREAD

**Issue by siddhsql** [jbellis/jvector#115]
how do I remove a vector from the index?

**Comment by jbellis** [comment]
Hi there,

Currently this isn't directly supported because in Cassandra we rebuild the index at compaction time and evict obsolete rows then.  However, it would be straightforward to add native deletes to jvector using NN descent.  GPT explains: https://chat.openai.com/share/936ad210-7ae7-49ac-9520-c83a1ea67a09

What is your use case?

**Comment by siddhsql** [comment]
Hi,

thanks for the reply. the use-case is simply to undo a mistake.

**Comment by lvca** [comment]
If this becomes a feature request, +1

**Comment by jbellis** [comment]
I looked a bit deeper into this.

1. NN descent is in fact easy
1. Connections are not always symmetrical, we have to scan the entire graph to remove the target from all the edges
1. removing nodes breaks assumption that node count = max node id (I think you can ignore this if you only want the in-memory piece)
1. making sure that no concurrent insert adds the removed node as a neighbor while it's in the process of being removed, without adding a bunch of overhead for the happy path, is tricky

looks like it makes more sense to just add the node to a deletion list, then implement a cleanup method that does the remove + repair in bulk.  This addresses 2 and 4.

then at write time, we can renumber nodes to address 3.

**Comment by siddhsql** [comment]
Ok, Jonathan thanks for looking into it.
