### ISSUE TITLE
Refactor SearchResult to avoid NodeScore[] allocations

### ISSUE THREAD

**Issue by jkni** [jbellis/jvector#227]
As described by jbellis:
```
I was never happy about reallocating to a NodeScore[] and now it's even more obviously extra work for no benefit

How about this?

SearchResult adds getNode(i), getScore(i) methods. Internal storage is int[] and vector[]

Move nodesCopy logic and GS.extractScores into an SR static method returning SR

(followup ticket is fine)
```

**Comment by jbellis** [comment]
... It's actually not obvious to me what the best solution is here.

1. Implement a custom sort that sorts the int[] and vector[] in place while preserving correspondance.
2. Implement a custom radix sort based on score * Int.MAX_VALUE.
3. Allocate an indices array and sort that with a custom comparator.  Don't need to move the original data around, just go through the indices array for getNode, getScore.
4. Go up a level, int[] and VectorFloat are the wrong level of abstraction, instead we should inject the corrected scores into the NodeQueue and let the caller pull out just the ones needed instead of sorting the whole set

I like #4 a lot but it's harder to fit native code into.

**Comment by jbellis** [comment]
That said, profiling says that the NodeScore[] copy is roughly 0.1% as expensive as reading the vectors and computing the full precision scores.  So I'm going to close this as premature optimization.
